{% set name = "lsstdesc-env" %}
{% set version = "0.0.1" %}
{% set build_number = 0 %}

package:
  name: {{ name }}
  version: {{ version }}

build:
  skip: True         # [python_impl == 'pypy' or win]
  number: {{ build_number }}

requirements:
  run:
    - astroplan
    - astropy
    - bokeh
    - camb
    - cmake
    - conda
    - cookiecutter
    - corner
    - dask
    - dask-mpi
    - dask-jobqueue
    - datashader 
    - dustmaps
    - eigen
    - emcee
    - extinction
    - fastparquet
    - fitsio
    - flake8
    - galsim
    - google-cloud-bigquery  
    - graphviz
    - gsl
    - h5py
    - hdf5
    - healpy
    - healsparse
    - holoviews
    - ipdb
    - ipympl
    - jupyter
    - markupsafe
    - matplotlib
    - namaster
    - nose
    - numba
    - numpy
    - pandas
    - parsl
    - pip  
    - psycopg2
    - pyarrow
    - pybind11
    - pyccl
    - pymssql
    - pytables
    - pytest
    - python =3.8
    - python-snappy
    - sacc
    - scikit-image
    - scikit-learn
    - scipy
    - seaborn
    - snappy
    - sphinx
    - tabulate
    - treecorr
    - yaml

test:
  imports:
    - pyccl


about:
  home: https://github.com/conda-forge/lsstdesc.env-feedstock
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Metapackage to install the DESC's common software environment.

  description: | 
    This metapackage exists to define the DESC common software
    environment, including version specifications where needed, while allowing
    users flexibility when installing additional packages into the same environment.

extra:
  recipe-maintainers:
    - beckermr
    - heather999
